default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: tvbach
  password: 11112000

development:
  <<: *default
  database: sample_app_dev
production:
  <<: *default
  database: sample_app_pro
